name: Lint

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Check formatting (gofmt)
        run: |
          files="$(gofmt -l .)"
          if [ -n "$files" ]; then
            echo "Unformatted files:"
            echo "$files"
            exit 1
          fi

      - name: Go vet
        run: go vet ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.2
          args: --timeout=5m

