name: Lint

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Run golangci-lint (GitHub action)
        uses: http://github.com/golangci/golangci-lint-action@v8
        with:
          version: v2.1.2
          args: --timeout=5m

